### ISSUE TITLE
Strict DI issue

### ISSUE THREAD

**Issue by ghost** [arielfaur/ionic-sidetabs#1]
Hi
Nice component, but when i use in my ionic app, where strict di is enabled, it fails because for the ionicSideTab controller you didn't inject properly the dependencies

Error: [$injector:strictdi] function($scope, $element) is not using explicit annotation and cannot be invoked in strict mode

**Comment by arielfaur** [comment]
You are right. Thanks for reporting! 
Will try to fix it this afternoon.

**Comment by arielfaur** [comment]
I've just pushed a new release with the DI fix. Let me know if it's alright now.

**Comment by ghost** [comment]
Yep. All good
Tks
