### ISSUE TITLE
How to dynamically expand a tab

### ISSUE THREAD

**Issue by AdrienDC** [arielfaur/ionic-sidetabs#5]
Hi @arielfaur , hny !
I was wondering if it's possible to programatically expand a tab. I explain myself, I would like the user to  update his settings in on side just after login for the first time so instead of expanding the tab himself, it would be nice if I can show him the way.

Thanks

**Comment by arielfaur** [comment]
Happy new year @AdrienDC !
That is not implemented yet. But I see how that could be useful! I hope I can get to it anytime soon. I need to catch up with the issue list :)

**Comment by AdrienDC** [comment]
Hello Ariel, 
by chance, did you have time to look at it? 
I'm trying to get the ion-side-tab list from the onTap function to generate an onTap on other elements expanded but didn't managed to do it with document.querySelector('ion-side-tab').. It's giving me elements but I can't onTap on it.

**Comment by arielfaur** [comment]
Hi @AdrienDC 

Sorry it took me so long to get back to this. I have updated the module to v1.1.0 which now supports dynamically expanding/collapsing tabs.
Checkout the updated codepen in the documentation. Let me know if you see any issues.

**Comment by AdrienDC** [comment]
Thank you so muchfor your quick reply @arielfaur ! I'll give a try this week.

**Comment by AdrienDC** [comment]
The codePen is not workng on my side: http://codepen.io/arielfaur/pen/PqrEBZ

**Comment by arielfaur** [comment]
That's weird. Works perfectly on my browser and on Android. Do you see any
errors?

**Comment by AdrienDC** [comment]
yes weird, I'm using Chrome... On Android it works well but the icon is not switched back correctly when I collapse dynamically (the arrow stays).

```
    $scope.tabCollapse = function(index) {
        console.log('Tab ' + index + ' collapsed');
        $scope.tab.expand0 = false;
        $scope.tab.expand1 = false;
        $scope.tab.expand2 = false;
        $scope.tab.expand3 = false;
    };
```

**Comment by arielfaur** [comment]
Maybe you could create a codepen and upload your code so I can look at it.

**Comment by AdrienDC** [comment]
yeah sure, http://codepen.io/anon/pen/NNNJOo
Basically I just want to collapse all tabs when one is manually collapsed but by doing this way in the codepen, the icon is not correctly reverted back for those dynamically collapsed. The one I tap on has the correct icon obviously.

**Comment by arielfaur** [comment]
Hi @AdrienDC 
I've just pushed a new release and updated the example to work better with dynamic tabs. Check out this codepen, I believe this is what you are trying to achieve: http://codepen.io/arielfaur/pen/PqrEBZ

**Comment by AdrienDC** [comment]
Thanks Ariel, this is exactly what I was looking for :+1: Awesome job !
