### ISSUE TITLE
allow-mid-range 

### ISSUE THREAD

**Issue by AdrienDC** [arielfaur/ionic-sidetabs#6]
Hi,
would it be possible to add the extra feature allow-mid-range like it's done for pullup?
If the user manually display the sidetabs, it's sometimes difficult to put it back correctly.

Thanks

**Comment by arielfaur** [comment]
Hi @AdrienDC 
Since you closed this issue I assume you changed your mind?

**Comment by AdrienDC** [comment]
hi @arielfaur , yes thanks I don't need it anymore
